#!/usr/bin/env bash
cd `dirname $0`
git pull

svn co https://svn.felspar.com/external/Boost
Boost/install `lsb_release -cs`
svn co https://svn.felspar.com/external/OpenSSL

svn co https://svn.felspar.com/public/fost-base/trunk/fost-base

metachatr/compile $*
